# License:
# **********************************************
# 
# src/Code/Project/Kthura_Transfer_SS2.ini
# (c) Jeroen Broks, 2026, All Rights Reserved.
# 
# This file contains material that is related
# to a storyline that is which is strictly
# copyrighted to Jeroen Broks.
# 
# This file may only be used in an unmodified
# form with an unmodified version of the
# software this file belongs to.
# 
# You may use this file for your study to see
# how I solved certain things in the creation
# of this project to see if you find valuable
# leads for the creation of your own.
# 
# Mostly this file comes along with a project
# that is for most part released under an
# open source license and that means that if
# you use that code with this file removed
# from it, you can use it under that license.
# Please check out the other files to find out
# which license applies.
# 
# This file comes 'as-is' and in no possible
# way the author can be held responsible of
# any form of damages that may occur due to
# the usage of this file
# 
# 
# **********************************************
# 
# 
# version: 26.04.30
# 
# End License
# Kthura Transfer Project File

[AUTHORS]
ANARRES=anarres
BARNHEARTOWL=barnheartowl
EVENT HORIZON TELESCOPE=Event Horizon Telescope
FINAO123=finao123
GDJ=GDJ
GRAMZON=gramzon
HATALAR=hatalar
JEROEN P. BROKS=Tricky Transfer
JONATA=Jonata
JUHELLE=Juhelle
MAN OF STEEL=Man of Steel
MOHAMMED IBRAHIM=Mohammed Ibrahim
RFC1394=rfc1394
SKURIAN25=Skurian25
VICIOUS SPEED=Vicious Speed
WARSZAWIANKA=warszawianka
[MAPMETA]
ALL=Y
ANY=Y
[ORIGINAL]
KTHURADIR=/media/tricky/Scyndi/Projects/Applications/Apollo/Games/Star Story 2/src/Tricky Story/Kthura
TEXTUREJCR6=/media/tricky/Scyndi/Projects/Applications/Apollo/Games/Star Story 2/Debug/Star Story 2.jcr
[PROJECT]
CREATED=05 Apr 2026; 17:27:45
[RENAME]
000_BLACKBOX=000_BlackBox
001_HYPERLOOPSTATION=001_HyperloopStation
002_SLUMS=002_Slums
003_ASHLEY=003_Ashley
004_MUERTE=004_Muerte
005_DOKTORLAB=005_DoktorLab
006_SEWERS=006_Sewers
901_FEO=901_Feo
HAWK=Hawk
[TARGET]
AUTHOR=Jeroen P. Broks
KTHURADIR=src/Kthura
NOTES=May not be extracted without prior WRITTEN permission from Jeroen P. Broks
SOURCEASSETS=src/Assets
STORAGE=zlib
TEXTUREJCR6=/media/tricky/Scyndi/Projects/Applications/Scyndi/Star Story 2/Debug/Star Story - Episode 2 - The Virus Strikes Back.jql
[TEXCONV]
GFX/ACTORS/DOCTOR.SOUTH.JPBF=GFX/Actors/Doctor.South.jpbf
GFX/BOXTEXT/PORTRET/Z_WENDICKA/NAKED.PNG=GFX/BoxText/Portret/Z_Wendicka/Naked.png
GFX/COMBAT/ARENA/BLACK HOLE.PNG=GFX/Combat/Arena/Black Hole.png
GFX/COMBAT/BUBBLES/BACKSIDE.PNG=GFX/Combat/Bubbles/Backside.png
GFX/COMBAT/FLD/BOSS.PNG=GFX/Combat/Fld/Boss.png
GFX/INTRO/PHANTASARPRODUCTIONS.PNG=GFX/Intro/PhantasarProductions.png
GFX/INTRO/STARFIELD.PNG=GFX/Intro/Starfield.png
GFX/NPC/DIVERSEN/STORK.PNG=GFX/NPC/Diversen/Stork.png
GFX/NPC/JI/JI - GREEN ALIEN WITH LONG MOSS HAIR.PNG=GFX/NPC/Ji/Ji - Green Alien With Long Moss Hair.png
GFX/NPC/METEOR/SECURITY HUMAN FEMALE.PNG=GFX/NPC/METEOR/Security Human Female.png
GFX/NPC/METEOR/SECURITY HUMAN MALE 2.PNG=GFX/NPC/METEOR/Security Human Male 2.png
GFX/NPC/METEOR/SECURITY HUMAN MALE.PNG=GFX/NPC/METEOR/Security Human Male.png
GFX/NPC/METEOR/SECURITY VERTIAN FEMALE.PNG=GFX/NPC/METEOR/Security Vertian Female.png
GFX/NPC/STORY/ANGEL.PNG=GFX/NPC/Story/Angel.png
GFX/NPC/STORY/BSURL.PNG=GFX/NPC/Story/Bsurl.png
GFX/NPC/STORY/HEIJN.PNG=GFX/NPC/Story/Heijn.png
GFX/NPC/STORY/HELMUT.PNG=GFX/NPC/Story/Helmut.png
GFX/NPC/STORY/JEROEN.PNG=GFX/NPC/Story/Jeroen.png
GFX/NPC/STORY/KLAHRE IN UNIFORM.PNG=GFX/NPC/Story/Klahre in uniform.png
GFX/NPC/STORY/QUINO.PNG=GFX/NPC/Story/Quino.png
GFX/NPC/STORY/SCOTT.PNG=GFX/NPC/Story/Scott.png
GFX/NPC/VERTIAN/MALE.PNG=GFX/NPC/Vertian/Male.png
GFX/NPC/VULPINS/VULPIN FEMALE BLUE SKIRT.PNG=GFX/NPC/Vulpins/Vulpin Female Blue Skirt.png
GFX/NPC/VULPINS/VULPIN FEMALE RED DRESS.PNG=GFX/NPC/Vulpins/Vulpin Female Red Dress.png
GFX/TEXTURES/AD/IRREVERSIBEL.PNG=GFX/Textures/Ad/Irreversibel.png
GFX/TEXTURES/BAR/BAR.PNG=GFX/Textures/Bar/Bar.png
GFX/TEXTURES/BAR/BARKURK.PNG=GFX/Textures/Bar/Barkurk.png
GFX/TEXTURES/BAR/TAP.PNG=GFX/Textures/Bar/Tap.png
GFX/TEXTURES/BRICK/BRICK004.PNG=GFX/TextureS/Brick/brick004.png
GFX/TEXTURES/BRICK/BRICK033.PNG=GFX/TextureS/Brick/brick033.png
GFX/TEXTURES/CARPET/DARK AMBER.PNG=GFX/Textures/Carpet/Dark Amber.png
GFX/TEXTURES/DECORATION/27.PNG=GFX/Textures/Decoration/27.png
GFX/TEXTURES/DECORATION/CAFE WERELDPIJN.PNG=GFX/Textures/Decoration/Cafe Wereldpijn.png
GFX/TEXTURES/DOOR/BARS.PNG=GFX/Textures/Door/Bars.png
GFX/TEXTURES/DOOR/DOOR 64X64.PNG=GFX/Textures/Door/Door 64x64.png
GFX/TEXTURES/DOOR/METAL/BAY DOOR.PNG=GFX/TextureS/Door/Metal/Bay Door.png
GFX/TEXTURES/DOOR/METAL/HYPERLOOP GATE DOOR.PNG=GFX/TextureS/Door/Metal/Hyperloop Gate Door.png
GFX/TEXTURES/FLOOR/DGREY080.PNG=GFX/TextureS/Floor/dgrey080.png
GFX/TEXTURES/FLOOR/DROCK047.PNG=GFX/TextureS/Floor/drock047.png
GFX/TEXTURES/FLOOR/LBLUE138.JPG=GFX/TextureS/Floor/lblue138.jpg
GFX/TEXTURES/FLOOR/ORANG032.PNG=GFX/TextureS/Floor/orang032.png
GFX/TEXTURES/FLOOR/WITTE DIAGONALE TEGELS.PNG=GFX/TextureS/Floor/Witte Diagonale Tegels.png
GFX/TEXTURES/FURNITURE/BED WOOD.PNG=GFX/Textures/Furniture/Bed Wood.png
GFX/TEXTURES/FURNITURE/BLACK ROUND TABLE.PNG=GFX/Textures/Furniture/Black Round Table.png
GFX/TEXTURES/FURNITURE/BUREAUSTOEL.PNG=GFX/Textures/furniture/Bureaustoel.png
GFX/TEXTURES/FURNITURE/GLASS TABLE.PNG=GFX/Textures/Furniture/Glass Table.png
GFX/TEXTURES/FURNITURE/MEETING TABLE.PNG=GFX/Textures/Furniture/Meeting table.png
GFX/TEXTURES/FURNITURE/ROLL DESK.PNG=GFX/Textures/Furniture/Roll desk.png
GFX/TEXTURES/FURNITURE/SOFA.PNG=GFX/Textures/Furniture/Sofa.png
GFX/TEXTURES/FURNITURE/WOODEN CHAIR.PNG=GFX/Textures/FURNITURE/Wooden chair.png
GFX/TEXTURES/GRAFITTI/FUCK THE SYSTEM.PNG=GFX/Textures/Grafitti/Fuck The System.png
GFX/TEXTURES/HALFHOUT/PAARS.PNG=GFX/Textures/Halfhout/Paars.png
GFX/TEXTURES/HALFHOUT/PAARS_LV.PNG=GFX/Textures/Halfhout/Paars_LV.png
GFX/TEXTURES/HALFHOUT/PAARS_RV.PNG=GFX/Textures/Halfhout/Paars_RV.png
GFX/TEXTURES/HALFHOUT/RAAM.PNG=GFX/Textures/Halfhout/Raam.png
GFX/TEXTURES/HALFHOUT/VAAL GROEN.PNG=GFX/Textures/Halfhout/Vaal Groen.png
GFX/TEXTURES/HAWK/BED.PNG=GFX/TEXTURES/HAWK/BED.PNG
GFX/TEXTURES/HAWK/BRIDGEWALL.PNG=GFX/TextureS/Hawk/BridgeWall.png
GFX/TEXTURES/HAWK/DEKEN.PNG=GFX/TEXTURES/HAWK/DEKEN.PNG
GFX/TEXTURES/HAWK/SCHUIFDEUR.PNG=gfx/textures/hawk/Schuifdeur.png
GFX/TEXTURES/HAWK/SCREENFRAME.PNG=GFX/TEXTURES/HAWK/SCREENFRAME.PNG
GFX/TEXTURES/HAWK/TERMINAL.PNG=GFX/Textures/Hawk/Terminal.png
GFX/TEXTURES/HOUTEN RAND/HOUTEN RAND - HORIZONTAAL.PNG=GFX/Textures/Houten Rand/Houten rand - Horizontaal.png
GFX/TEXTURES/HOUTEN RAND/HOUTEN RAND - VERTICAAL.PNG=GFX/Textures/Houten Rand/Houten rand - Verticaal.png
GFX/TEXTURES/JUNK/JONATA-ORGANIC.PNG=gfx/textures/junk/jonata-Organic.png
GFX/TEXTURES/JUNK/JONATA-SARDINE-CAN.PNG=gfx/textures/junk/jonata-Sardine-Can.png
GFX/TEXTURES/JUNK/JUNK/MAIL-MARK-JUNK.PNG=GFX/Textures/Junk/Junk/mail-mark-junk.png
GFX/TEXTURES/JUNK/JUNK/RUSTYGEAR.PNG=GFX/Textures/Junk/Junk/rustygear.png
GFX/TEXTURES/JUNK/JUNK/TRASH BAG.PNG=GFX/Textures/Junk/Junk/Trash Bag.png
GFX/TEXTURES/LAB/DESK.PNG=GFX/Textures/Lab/Desk.png
GFX/TEXTURES/LAB/DIGITAL MICROSCOPE CUT.PNG=GFX/TeXtUrEs/Lab/Digital Microscope Cut.png
GFX/TEXTURES/MEDALS/SEIN/1.PNG=GFX/Textures/Medals/Sein/1.png
GFX/TEXTURES/MEDALS/SEIN/2.PNG=GFX/TEXTURES/Medals/Sein/2.png
GFX/TEXTURES/MEDALS/SEIN/3.PNG=GFX/Textures/Medals/Sein/3.png
GFX/TEXTURES/METAL/BBX_METAL.PNG=GFX/TextureS/Metal/BBX_Metal.png
GFX/TEXTURES/METAL/METAL027.PNG=GFX/TextureS/Metal/metal027.png
GFX/TEXTURES/METALFLOOR/METAL FLOOR.PNG=GFX/TextureS/MetalFloor/Metal Floor.png
GFX/TEXTURES/PUZZLES/SUDOKU/MUERTE/EMPTY.PNG=GFX/Textures/Puzzles/Sudoku/Muerte/Empty.png
GFX/TEXTURES/PUZZLES/SUDOKU/MUERTE/SOLUTION.PNG=GFX/Textures/Puzzles/Sudoku/Muerte/Solution.png
GFX/TEXTURES/PUZZLES/SUDOKU/NUMS/0.PNG=Fonts/Ryanna.jfbf/48.png
GFX/TEXTURES/SIGNS/HYPERLOOP/SIGN1.PNG=GFX/Textures/Signs/Hyperloop/Sign1.png
GFX/TEXTURES/SIGNS/HYPERLOOP/SIGN2.PNG=GFX/Textures/Signs/Hyperloop/Sign2.png
GFX/TEXTURES/SIGNS/HYPERLOOP/SIGN3.PNG=GFX/Textures/Signs/Hyperloop/Sign3.png
GFX/TEXTURES/SPECIAL/LADDER.PNG=GFX/Textures/Special/Ladder.png
GFX/TEXTURES/STAIRS/DOWN.PNG=GFX/Textures/Stairs/Down.png
GFX/TEXTURES/STAIRS/UP.PNG=GFX/Textures/Stairs/Up.png
GFX/TEXTURES/STONE/FLOOR.PNG=GFX/TextureS/Stone/Floor.png
GFX/TEXTURES/STONE/ROCKWALL.PNG=GFX/TextureS/Stone/RockWall.png
GFX/TEXTURES/STONE/ROCKWALL_LV.PNG=GFX/TextureS/Stone/RockWall_LV.png
GFX/TEXTURES/STONE/ROCKWALL_RV.PNG=GFX/TextureS/Stone/RockWall_RV.png
GFX/TEXTURES/SWITCH/LEFT.PNG=GFX/Textures/Switch/Left.png
GFX/TEXTURES/TRANSPORTER/BLUE BACKWALL.PNG=GFX/TEXTURES/TRANSPORTER/BLUE BACKWALL.PNG
GFX/TEXTURES/TRANSPORTER/BLUE BACKWALL_LV.PNG=GFX/TEXTURES/TRANSPORTER/BLUE BACKWALL_LV.PNG
GFX/TEXTURES/TRANSPORTER/BLUE BACKWALL_RV.PNG=GFX/TEXTURES/TRANSPORTER/BLUE BACKWALL_RV.PNG
GFX/TEXTURES/TRANSPORTER/SS_PAD.PNG=GFX/Textures/Transporter/SS_Pad.png
GFX/TEXTURES/WATER/WATER.PNG=GFX/TextureS/Water/water.png
GFX/TEXTURES/WHOLE/KITCHEN.PNG=GFX/Textures/Whole/Kitchen.png
GFX/TRANS/GENERAL.PNG=GFX/Trans/General.png
GFX/TRANS/RECOVER.PNG=GFX/Trans/Recover.png
GFX/TRANS/RETURNONLY.PNG=GFX/Trans/ReturnOnly.png
GFX/TREASURE/ARMS_CHEST.PNG=GFX/Treasure/ARMS_Chest.png
GFX/TREASURE/TREASURECHEST.PNG=GFX/Treasure/TreasureChest.png
[TRANSFER]
UNKNOWN_ALLOWED=Y
