# License:
# **********************************************
# 
# src/Code/Project/Kthura_Transfer_SS2.ini
# (c) Jeroen Broks, 2026, All Rights Reserved.
# 
# This file contains material that is related
# to a storyline that is which is strictly
# copyrighted to Jeroen Broks.
# 
# This file may only be used in an unmodified
# form with an unmodified version of the
# software this file belongs to.
# 
# You may use this file for your study to see
# how I solved certain things in the creation
# of this project to see if you find valuable
# leads for the creation of your own.
# 
# Mostly this file comes along with a project
# that is for most part released under an
# open source license and that means that if
# you use that code with this file removed
# from it, you can use it under that license.
# Please check out the other files to find out
# which license applies.
# 
# This file comes 'as-is' and in no possible
# way the author can be held responsible of
# any form of damages that may occur due to
# the usage of this file
# 
# 
# **********************************************
# 
# 
# version: 26.05.02 VII
# 
# End License
# Kthura Transfer Project File

[AUTHORS]
ANARRES=anarres
BARNHEARTOWL=barnheartowl
EVENT HORIZON TELESCOPE=Event Horizon Telescope
FINAO123=finao123
GDJ=GDJ
GRAMZON=gramzon
HATALAR=hatalar
HYPOCORE=hypocore
JEROEN P. BROKS=Tricky Transfer
JONATA=Jonata
JUHELLE=Juhelle
MAN OF STEEL=Man of Steel
MOHAMMED IBRAHIM=Mohammed Ibrahim
RFC1394=rfc1394
SKURIAN25=Skurian25
VICIOUS SPEED=Vicious Speed
WARSZAWIANKA=warszawianka
[MAPMETA]
ALL=Y
ANY=Y
[ORIGINAL]
KTHURADIR=/media/tricky/Scyndi/Projects/Applications/Apollo/Games/Star Story 2/src/Tricky Story/Kthura
TEXTUREJCR6=/media/tricky/Scyndi/Projects/Applications/Apollo/Games/Star Story 2/Debug/Star Story 2.jcr
[PROJECT]
CREATED=05 Apr 2026; 17:27:45
[RENAME]
000_BLACKBOX=000_BlackBox
001_HYPERLOOPSTATION=001_HyperloopStation
002_SLUMS=002_Slums
003_ASHLEY=003_Ashley
004_MUERTE=004_Muerte
005_DOKTORLAB=005_DoktorLab
006_SEWERS=006_Sewers
007_MULAN=007_Mulan
008_BFOC=008_BFOC
009_GLEVU_CORRIDOR=009_Glevu_Corridor
010_LETSGOBRANDON_TUNNEL=010_Letsgobrandon_Tunnel
011_LUYTEN=011_Luyten
012_SECRETSAFE=012_SecretSafe
013_BASEMENT=013_Basement
901_FEO=901_Feo
902_VAULT=902_Vault
991_CATWALKS=991_Catwalks
HAWK=Hawk
PHAN_ARRIVAL=Phan_Arrival
PHAN_DRAGON=Phan_Dragon
PHAN_ELFENROAD=Phan_ElfenRoad
PHAN_ISKARDERIU=Phan_Iskarderiu
[TARGET]
AUTHOR=Jeroen P. Broks
KTHURADIR=src/Kthura
NOTES=May not be extracted without prior WRITTEN permission from Jeroen P. Broks
SOURCEASSETS=src/Assets
STORAGE=zlib
TEXTUREJCR6=/media/tricky/Scyndi/Projects/Applications/Scyndi/Star Story 2/Debug/Star Story - Episode 2 - The Virus Strikes Back.jql
[TEXCONV]
GFX/ACTORS/DOCTOR.SOUTH.JPBF=GFX/Actors/Doctor.South.jpbf
GFX/ACTORS/Z_WENDICKA.SOUTH.JPBF=GFX/Actors/Z_Wendicka.South.jpbf
GFX/BOXTEXT/PORTRET/Z_WENDICKA/NAKED.PNG=GFX/BoxText/Portret/Z_Wendicka/Naked.png
GFX/COMBAT/ARENA/BLACK HOLE.PNG=GFX/Combat/Arena/Black Hole.png
GFX/COMBAT/BUBBLES/BACKSIDE.PNG=GFX/Combat/Bubbles/Backside.png
GFX/COMBAT/BUBBLES/FOE_A.PNG=GFX/Combat/Bubbles/Foe_A.png
GFX/COMBAT/FLD/BOSS.PNG=GFX/Combat/Fld/Boss.png
GFX/COMBAT/FOES/BOSS/BLOEMSCHOEN.PNG=GFX/Combat/Foes/Boss/Bloemschoen.png
GFX/COMBAT/FOES/BOSS/FERDY FUNHOUSE.PNG=GFX/Combat/Foes/Boss/Ferdy Funhouse.png
GFX/COMBAT/FOES/BOSS/KUIP.PNG=GFX/Combat/Foes/Boss/Kuip.png
GFX/COMBAT/FOES/PHANBOSS/BIGMAMASLIME.PNG=GFX/Combat/Foes/PhanBoss/BigMamaSlime.png
GFX/COMBAT/HEROES/ASHLEY.DEAD.PNG=GFX/Combat/Heroes/Ashley.Dead.png
GFX/INTRO/PHANTASARPRODUCTIONS.PNG=GFX/Intro/PhantasarProductions.png
GFX/INTRO/STARFIELD.PNG=GFX/Intro/Starfield.png
GFX/MAPSPOTS/TRAVEL.PNG=GFX/MapSpots/Travel.png
GFX/NPC/DIVERSEN/EXHURU.SOUTH.PNG=GFX/NPC/Diversen/ExHuRU.South.png
GFX/NPC/DIVERSEN/STORK.PNG=GFX/NPC/Diversen/Stork.png
GFX/NPC/HEROSPECIAL/KLAHRE_OP_BUREAUSTOEL_BFOC.PNG=GFX/NPC/HeroSpecial/Klahre_Op_Bureaustoel_BFOC.png
GFX/NPC/JI/JI - GREEN ALIEN WITH LONG MOSS HAIR.PNG=GFX/NPC/Ji/Ji - Green Alien With Long Moss Hair.png
GFX/NPC/METEOR/SECURITY HUMAN FEMALE.PNG=GFX/NPC/METEOR/Security Human Female.png
GFX/NPC/METEOR/SECURITY HUMAN MALE 2.PNG=GFX/NPC/METEOR/Security Human Male 2.png
GFX/NPC/METEOR/SECURITY HUMAN MALE.PNG=GFX/NPC/METEOR/Security Human Male.png
GFX/NPC/METEOR/SECURITY VERTIAN FEMALE.PNG=GFX/NPC/METEOR/Security Vertian Female.png
GFX/NPC/PHANTASAR/ASKLEPIA.PNG=GFX/NPC/Phantasar/Asklepia.png
GFX/NPC/PHANTASAR/GEDRIO FULLA.PNG=GFX/NPC/Phantasar/Gedrio Fulla.png
GFX/NPC/PHANTASAR/RACHEL.PNG=GFX/NPC/Phantasar/Rachel.png
GFX/NPC/PHANTASAR/RANDOM ELF FEMALE 1.PNG=GFX/NPC/Phantasar/Random Elf Female 1.png
GFX/NPC/PHANTASAR/RANDOM ELF FEMALE 2.PNG=GFX/NPC/Phantasar/Random Elf Female 2.png
GFX/NPC/PHANTASAR/RANDOM ELF MALE 1.PNG=GFX/NPC/Phantasar/Random Elf Male 1.png
GFX/NPC/PHANTASAR/RANDOM ELF MALE 2.PNG=GFX/NPC/Phantasar/Random Elf Male 2.png
GFX/NPC/PHANTASAR/ROSETTA.PNG=GFX/NPC/Phantasar/Rosetta.png
GFX/NPC/PHANTASAR/SASHA FUNDA.PNG=GFX/NPC/Phantasar/Sasha Funda.png
GFX/NPC/PHANTASAR/SAVE.PNG=GFX/NPC/Phantasar/Save.png
GFX/NPC/PHANTASAR/SCYNDI.PNG=GFX/NPC/Phantasar/Scyndi.png
GFX/NPC/STORY/ABEL.PNG=GFX/NPC/Story/Abel.png
GFX/NPC/STORY/ANGEL.PNG=GFX/NPC/Story/Angel.png
GFX/NPC/STORY/BSURL.PNG=GFX/NPC/Story/Bsurl.png
GFX/NPC/STORY/EFU MAN.PNG=GFX/NPC/Story/EFU Man.png
GFX/NPC/STORY/EMERALD.PNG=GFX/NPC/Story/Emerald.png
GFX/NPC/STORY/HEIJN.PNG=GFX/NPC/Story/Heijn.png
GFX/NPC/STORY/HELMUT.PNG=GFX/NPC/Story/Helmut.png
GFX/NPC/STORY/JEROEN.PNG=GFX/NPC/Story/Jeroen.png
GFX/NPC/STORY/KLAHRE IN UNIFORM.PNG=GFX/NPC/Story/Klahre in uniform.png
GFX/NPC/STORY/KRAAG.PNG=GFX/NPC/Story/Kraag.png
GFX/NPC/STORY/MARION.PNG=GFX/NPC/Story/Marion.png
GFX/NPC/STORY/MURRAT TEK.PNG=GFX/NPC/Story/Murrat Tek.png
GFX/NPC/STORY/QUINO.PNG=GFX/NPC/Story/Quino.png
GFX/NPC/STORY/RANCID MARC.PNG=GFX/NPC/Story/Rancid Marc.png
GFX/NPC/STORY/REYNARD.PNG=GFX/NPC/Story/Reynard.png
GFX/NPC/STORY/ROCK.PNG=GFX/NPC/Story/Rock.png
GFX/NPC/STORY/SCOTT.PNG=GFX/NPC/Story/Scott.png
GFX/NPC/VERTIAN/MALE.PNG=GFX/NPC/Vertian/Male.png
GFX/NPC/VULPINS/VULPIN FEMALE BLUE SKIRT.PNG=GFX/NPC/Vulpins/Vulpin Female Blue Skirt.png
GFX/NPC/VULPINS/VULPIN FEMALE RED DRESS.PNG=GFX/NPC/Vulpins/Vulpin Female Red Dress.png
GFX/TEXTURE/PHANTASAR/DUNGEON/GREY/ARCH + DOOR.PNG=GFX/Texture/Phantasar/Dungeon/Grey/Arch + Door.png
GFX/TEXTURE/PHANTASAR/DUNGEON/GREY/ARCH.PNG=GFX/Texture/Phantasar/Dungeon/Grey/Arch.png
GFX/TEXTURE/PHANTASAR/DUNGEON/GREY/EAST WALL.PNG=GFX/Texture/Phantasar/Dungeon/Grey/East Wall.png
GFX/TEXTURE/PHANTASAR/DUNGEON/GREY/FLOOR.PNG=GFX/Texture/Phantasar/Dungeon/Grey/Floor.png
GFX/TEXTURE/PHANTASAR/DUNGEON/GREY/NORTH WALL.PNG=GFX/Texture/Phantasar/Dungeon/Grey/North Wall.png
GFX/TEXTURE/PHANTASAR/DUNGEON/GREY/NORTH-EAST WALL (SCHUIN).PNG=GFX/Texture/Phantasar/Dungeon/Grey/North-East Wall (Schuin).png
GFX/TEXTURE/PHANTASAR/DUNGEON/GREY/NORTH-WEST WALL (SCHUIN).PNG=GFX/Texture/Phantasar/Dungeon/Grey/North-West Wall (Schuin).png
GFX/TEXTURE/PHANTASAR/DUNGEON/GREY/SOUTH WALL.PNG=GFX/Texture/Phantasar/Dungeon/Grey/South Wall.png
GFX/TEXTURE/PHANTASAR/DUNGEON/GREY/WEST WALL.PNG=GFX/Texture/Phantasar/Dungeon/Grey/West Wall.png
GFX/TEXTURE/PHANTASAR/OBJECTS/KAARS UIT.PNG=GFX/Texture/Phantasar/Objects/Kaars uit.png
GFX/TEXTURE/PHANTASAR/OBJECTS/TOORTS UIT.PNG=GFX/Texture/Phantasar/Objects/Toorts Uit.png
GFX/TEXTURES/AD/IRREVERSIBEL.PNG=GFX/Textures/Ad/Irreversibel.png
GFX/TEXTURES/BAR/BAR.PNG=GFX/Textures/Bar/Bar.png
GFX/TEXTURES/BAR/BARKURK.PNG=GFX/Textures/Bar/Barkurk.png
GFX/TEXTURES/BAR/TAP.PNG=GFX/Textures/Bar/Tap.png
GFX/TEXTURES/BFOC2960/LOGO.PNG=GFX/Textures/BFOC2960/Logo.png
GFX/TEXTURES/BLACK CORRIDOR/FLOOR.PNG=GFX/Textures/Black Corridor/Floor.png
GFX/TEXTURES/BLACK CORRIDOR/WC_SE.PNG=GFX/Textures/Black Corridor/WC_SE.png
GFX/TEXTURES/BLACK CORRIDOR/WC_SW.PNG=GFX/Textures/Black Corridor/WC_SW.png
GFX/TEXTURES/BLACK CORRIDOR/WR_E.PNG=GFX/Textures/Black Corridor/WR_E.png
GFX/TEXTURES/BLACK CORRIDOR/WR_N.PNG=GFX/Textures/Black Corridor/WR_N.png
GFX/TEXTURES/BLACK CORRIDOR/WR_S.PNG=GFX/Textures/Black Corridor/WR_S.png
GFX/TEXTURES/BLACK CORRIDOR/WR_W.PNG=GFX/Textures/Black Corridor/WR_W.png
GFX/TEXTURES/BLACK CORRIDOR/WS_NE.PNG=GFX/Textures/Black Corridor/WS_NE.png
GFX/TEXTURES/BLACK CORRIDOR/WS_NW.PNG=GFX/Textures/Black Corridor/WS_NW.png
GFX/TEXTURES/BLACK CORRIDOR/WS_SE.PNG=GFX/Textures/Black Corridor/WS_SE.png
GFX/TEXTURES/BLACK CORRIDOR/WS_SW.PNG=GFX/Textures/Black Corridor/WS_SW.png
GFX/TEXTURES/BRICK/BRICK004.PNG=GFX/TextureS/Brick/brick004.png
GFX/TEXTURES/BRICK/BRICK033.PNG=GFX/TextureS/Brick/brick033.png
GFX/TEXTURES/BRICK/BRICK067 (BIG _ DARK RED).PNG=GFX/TextureS/Brick/brick067 (big _ dark red).png
GFX/TEXTURES/CARPET/DARK AMBER.PNG=GFX/Textures/Carpet/Dark Amber.png
GFX/TEXTURES/DECORATION/27.PNG=GFX/Textures/Decoration/27.png
GFX/TEXTURES/DECORATION/CAFE WERELDPIJN.PNG=GFX/Textures/Decoration/Cafe Wereldpijn.png
GFX/TEXTURES/DOOR/BARS.PNG=GFX/Textures/Door/Bars.png
GFX/TEXTURES/DOOR/DOOR 64X64.PNG=GFX/Textures/Door/Door 64x64.png
GFX/TEXTURES/DOOR/METAL/BAY DOOR.PNG=GFX/TextureS/Door/Metal/Bay Door.png
GFX/TEXTURES/DOOR/METAL/HYPERLOOP GATE DOOR.PNG=GFX/TextureS/Door/Metal/Hyperloop Gate Door.png
GFX/TEXTURES/DOOR/SCHUIFDEUR.PNG=GFX/Textures/Facility/SchuifDeur.png
GFX/TEXTURES/EFU/LOGO.PNG=GFX/Textures/EFU/Logo.png
GFX/TEXTURES/FACILITY/DOORPOST_EAST.PNG=GFX/Textures/Facility/DoorPost_East.png
GFX/TEXTURES/FACILITY/DOORPOST_WEST.PNG=GFX/Textures/Facility/DoorPost_West.png
GFX/TEXTURES/FACILITY/EAST.PNG=GFX/Textures/Facility/East.png
GFX/TEXTURES/FACILITY/FLOOR.PNG=GFX/Textures/Facility/Floor.png
GFX/TEXTURES/FACILITY/NORTH-EAST ENDING.PNG=GFX/Textures/Facility/North-East Ending.png
GFX/TEXTURES/FACILITY/NORTH-EAST.PNG=GFX/Textures/Facility/North-East.png
GFX/TEXTURES/FACILITY/NORTH-WEST ENDING.PNG=GFX/Textures/Facility/North-West Ending.png
GFX/TEXTURES/FACILITY/NORTH-WEST.PNG=GFX/Textures/Facility/North-West.png
GFX/TEXTURES/FACILITY/NORTH.PNG=GFX/Textures/Facility/North.png
GFX/TEXTURES/FACILITY/SCHUIFDEUR.PNG=GFX/Textures/Facility/SchuifDeur.png
GFX/TEXTURES/FACILITY/SOUTH-EAST ENDING.PNG=GFX/Textures/Facility/South-East Ending.png
GFX/TEXTURES/FACILITY/SOUTH-EAST.PNG=GFX/Textures/Facility/South-East.png
GFX/TEXTURES/FACILITY/SOUTH-WEST ENDING.PNG=GFX/Textures/Facility/South-West Ending.png
GFX/TEXTURES/FACILITY/SOUTH-WEST.PNG=GFX/Textures/Facility/South-West.png
GFX/TEXTURES/FACILITY/SOUTH.PNG=GFX/Textures/Facility/South.png
GFX/TEXTURES/FACILITY/WEST.PNG=GFX/Textures/Facility/West.png
GFX/TEXTURES/FLOOR/DGREY080.PNG=GFX/TextureS/Floor/dgrey080.png
GFX/TEXTURES/FLOOR/DROCK047.PNG=GFX/TextureS/Floor/drock047.png
GFX/TEXTURES/FLOOR/LBLUE138.JPG=GFX/TextureS/Floor/lblue138.jpg
GFX/TEXTURES/FLOOR/ORANG032.PNG=GFX/TextureS/Floor/orang032.png
GFX/TEXTURES/FLOOR/ROOSTERVLOER.PNG=GFX/TextureS/Floor/RoosterVloer.png
GFX/TEXTURES/FLOOR/WITTE DIAGONALE TEGELS.PNG=GFX/TextureS/Floor/Witte Diagonale Tegels.png
GFX/TEXTURES/FOREST/BLOEMETJE.PNG=GFX/Textures/Forest/Bloemetje.png
GFX/TEXTURES/FOREST/GRAS - GROEN.PNG=GFX/Textures/Forest/Gras - Groen.png
GFX/TEXTURES/FOREST/GRASS1.PNG=GFX/Textures/Forest/Grass1.png
GFX/TEXTURES/FOREST/GRASS2.PNG=y
GFX/TEXTURES/FOREST/SPAR.PNG=GFX/Textures/Forest/Spar.png
GFX/TEXTURES/FOREST/STRUIK.PNG=GFX/Textures/Forest/Struik.png
GFX/TEXTURES/FURNITURE/BED WOOD.PNG=GFX/Textures/Furniture/Bed Wood.png
GFX/TEXTURES/FURNITURE/BLACK ROUND TABLE.PNG=GFX/Textures/Furniture/Black Round Table.png
GFX/TEXTURES/FURNITURE/BUREAUSTOEL.PNG=GFX/Textures/furniture/Bureaustoel.png
GFX/TEXTURES/FURNITURE/CLOCK.PNG=gfx/textures/furniture/clock.png
GFX/TEXTURES/FURNITURE/GLASS TABLE.PNG=GFX/Textures/Furniture/Glass Table.png
GFX/TEXTURES/FURNITURE/MEETING TABLE.PNG=GFX/Textures/Furniture/Meeting table.png
GFX/TEXTURES/FURNITURE/ROLL DESK.PNG=GFX/Textures/Furniture/Roll desk.png
GFX/TEXTURES/FURNITURE/SCREEN.PNG=GFX/Textures/Furniture/Screen.png
GFX/TEXTURES/FURNITURE/SOFA.PNG=GFX/Textures/Furniture/Sofa.png
GFX/TEXTURES/FURNITURE/WOODEN CHAIR.PNG=GFX/Textures/FURNITURE/Wooden chair.png
GFX/TEXTURES/GRAFITTI/FUCK THE SYSTEM.PNG=GFX/Textures/Grafitti/Fuck The System.png
GFX/TEXTURES/GROT/E.PNG=GFX/Textures/Grot/E.png
GFX/TEXTURES/GROT/F.PNG=GFX/Textures/Grot/F.png
GFX/TEXTURES/GROT/N.PNG=GFX/Textures/Grot/N.png
GFX/TEXTURES/GROT/NE.PNG=GFX/Textures/Grot/NE.png
GFX/TEXTURES/GROT/NW.PNG=GFX/Textures/Grot/NW.png
GFX/TEXTURES/GROT/S.PNG=GFX/Textures/Grot/S.png
GFX/TEXTURES/GROT/SE.PNG=GFX/Textures/Grot/SE.png
GFX/TEXTURES/GROT/STALAGMITE.PNG=GFX/Textures/Grot/Stalagmite.png
GFX/TEXTURES/GROT/SW.PNG=GFX/Textures/Grot/SW.png
GFX/TEXTURES/GROT/W.PNG=GFX/Textures/Grot/W.png
GFX/TEXTURES/HALFHOUT/PAARS.PNG=GFX/Textures/Halfhout/Paars.png
GFX/TEXTURES/HALFHOUT/PAARS_LV.PNG=GFX/Textures/Halfhout/Paars_LV.png
GFX/TEXTURES/HALFHOUT/PAARS_RV.PNG=GFX/Textures/Halfhout/Paars_RV.png
GFX/TEXTURES/HALFHOUT/RAAM.PNG=GFX/Textures/Halfhout/Raam.png
GFX/TEXTURES/HALFHOUT/VAAL GROEN.PNG=GFX/Textures/Halfhout/Vaal Groen.png
GFX/TEXTURES/HAWK/BED.PNG=GFX/TEXTURES/HAWK/BED.PNG
GFX/TEXTURES/HAWK/BRIDGEWALL.PNG=GFX/TextureS/Hawk/BridgeWall.png
GFX/TEXTURES/HAWK/DEKEN.PNG=GFX/TEXTURES/HAWK/DEKEN.PNG
GFX/TEXTURES/HAWK/SCHUIFDEUR.PNG=gfx/textures/hawk/Schuifdeur.png
GFX/TEXTURES/HAWK/SCREENFRAME.PNG=GFX/TEXTURES/HAWK/SCREENFRAME.PNG
GFX/TEXTURES/HAWK/TERMINAL.PNG=GFX/Textures/Hawk/Terminal.png
GFX/TEXTURES/HEK/STEEN.PNG=GFX/Textures/Hek/Steen.png
GFX/TEXTURES/HOUTEN RAND/HOUTEN RAND - HORIZONTAAL.PNG=GFX/Textures/Houten Rand/Houten rand - Horizontaal.png
GFX/TEXTURES/HOUTEN RAND/HOUTEN RAND - VERTICAAL.PNG=GFX/Textures/Houten Rand/Houten rand - Verticaal.png
GFX/TEXTURES/ISKARDERIU/BED.PNG=GFX/Textures/Iskarderiu/Bed.png
GFX/TEXTURES/ISKARDERIU/BORDJE/INN.PNG=GFX/Textures/Iskarderiu/Bordje/Inn.png
GFX/TEXTURES/ISKARDERIU/BORDJE/ITEMS.PNG=GFX/Textures/Iskarderiu/Bordje/Items.png
GFX/TEXTURES/ISKARDERIU/BORDJE/WAPENS.PNG=GFX/Textures/Iskarderiu/Bordje/Wapens.png
GFX/TEXTURES/ISKARDERIU/COMPLEET HUIS (ELF MODEL).PNG=GFX/Textures/Iskarderiu/Compleet huis (Elf model).png
GFX/TEXTURES/ISKARDERIU/EEN KAST VOL MET POTTEN.PNG=GFX/Textures/Iskarderiu/Een kast vol met potten.png
GFX/TEXTURES/ISKARDERIU/STOEL - ACHTERZIJDE.PNG=GFX/Textures/Iskarderiu/Stoel - Achterzijde.png
GFX/TEXTURES/ISKARDERIU/STOEL - VOORZIJDE.PNG=GFX/Textures/Iskarderiu/Stoel - Voorzijde.png
GFX/TEXTURES/ISKARDERIU/SWORDS/COMBINED.PNG=GFX/Textures/Iskarderiu/Swords/Combined.png
GFX/TEXTURES/ISKARDERIU/TOONBANK.PNG=GFX/Textures/Iskarderiu/Toonbank.png
GFX/TEXTURES/ISKARDERIU/WAND - LINKS.PNG=GFX/Textures/Iskarderiu/Wand - Links.png
GFX/TEXTURES/ISKARDERIU/WAND - RECHTS.PNG=GFX/Textures/Iskarderiu/Wand - Rechts.png
GFX/TEXTURES/ISKARDERIU/WAND.PNG=GFX/Textures/Iskarderiu/Wand.png
GFX/TEXTURES/JUNK/JONATA-ORGANIC.PNG=gfx/textures/junk/jonata-Organic.png
GFX/TEXTURES/JUNK/JONATA-SARDINE-CAN.PNG=gfx/textures/junk/jonata-Sardine-Can.png
GFX/TEXTURES/JUNK/JUNK/MAIL-MARK-JUNK.PNG=GFX/Textures/Junk/Junk/mail-mark-junk.png
GFX/TEXTURES/JUNK/JUNK/RUSTYGEAR.PNG=GFX/Textures/Junk/Junk/rustygear.png
GFX/TEXTURES/JUNK/JUNK/TRASH BAG.PNG=GFX/Textures/Junk/Junk/Trash Bag.png
GFX/TEXTURES/LAB/DESK.PNG=GFX/Textures/Lab/Desk.png
GFX/TEXTURES/LAB/DIGITAL MICROSCOPE CUT.PNG=GFX/TeXtUrEs/Lab/Digital Microscope Cut.png
GFX/TEXTURES/MEDALS/SEIN/1.PNG=GFX/Textures/Medals/Sein/1.png
GFX/TEXTURES/MEDALS/SEIN/2.PNG=GFX/TEXTURES/Medals/Sein/2.png
GFX/TEXTURES/MEDALS/SEIN/3.PNG=GFX/Textures/Medals/Sein/3.png
GFX/TEXTURES/METAL/BBX_METAL.PNG=GFX/TextureS/Metal/BBX_Metal.png
GFX/TEXTURES/METAL/METAL027.PNG=GFX/TextureS/Metal/metal027.png
GFX/TEXTURES/METALFLOOR/METAL FLOOR.PNG=GFX/TextureS/MetalFloor/Metal Floor.png
GFX/TEXTURES/MOVING FLOWERS/ANIMATED BLUE.JPBF=GFX/Textures/Moving Flowers/Animated Blue.jpbf
GFX/TEXTURES/MOVING FLOWERS/ANIMATED PURPLE.JPBF=GFX/Textures/Moving Flowers/Animated Purple.jpbf
GFX/TEXTURES/MOVING FLOWERS/ANIMATED RED.JPBF=GFX/Textures/Moving Flowers/Animated Red.jpbf
GFX/TEXTURES/PHANTASAR/KAPOT MEUBILAIR/BANK.PNG=GFX/Textures/Phantasar/Kapot meubilair/Bank.png
GFX/TEXTURES/PHANTASAR/KAPOT MEUBILAIR/HEMELBED.PNG=GFX/Textures/Phantasar/Kapot meubilair/Hemelbed.png
GFX/TEXTURES/PHANTASAR/KAPOT MEUBILAIR/TAFEL.PNG=GFX/Textures/Phantasar/Kapot meubilair/Tafel.png
GFX/TEXTURES/PUZZLES/SUDOKU/MUERTE/EMPTY.PNG=GFX/Textures/Puzzles/Sudoku/Muerte/Empty.png
GFX/TEXTURES/PUZZLES/SUDOKU/MUERTE/SOLUTION.PNG=GFX/Textures/Puzzles/Sudoku/Muerte/Solution.png
GFX/TEXTURES/PUZZLES/SUDOKU/NUMS/0.PNG=Fonts/Ryanna.jfbf/48.png
GFX/TEXTURES/SIGNS/DUNGSIGN_PLAQUE.PNG=GFX/Textures/Signs/DungSign_Plaque.png
GFX/TEXTURES/SIGNS/HYPERLOOP/SIGN1.PNG=GFX/Textures/Signs/Hyperloop/Sign1.png
GFX/TEXTURES/SIGNS/HYPERLOOP/SIGN2.PNG=GFX/Textures/Signs/Hyperloop/Sign2.png
GFX/TEXTURES/SIGNS/HYPERLOOP/SIGN3.PNG=GFX/Textures/Signs/Hyperloop/Sign3.png
GFX/TEXTURES/SPECIAL/LADDER.PNG=GFX/Textures/Special/Ladder.png
GFX/TEXTURES/STAIRS/DOWN.PNG=GFX/Textures/Stairs/Down.png
GFX/TEXTURES/STAIRS/UP.PNG=GFX/Textures/Stairs/Up.png
GFX/TEXTURES/STONE/FLOOR.PNG=GFX/TextureS/Stone/Floor.png
GFX/TEXTURES/STONE/ROCKWALL.PNG=GFX/TextureS/Stone/RockWall.png
GFX/TEXTURES/STONE/ROCKWALL_LV.PNG=GFX/TextureS/Stone/RockWall_LV.png
GFX/TEXTURES/STONE/ROCKWALL_RV.PNG=GFX/TextureS/Stone/RockWall_RV.png
GFX/TEXTURES/SWITCH/LEFT.PNG=GFX/Textures/Switch/Left.png
GFX/TEXTURES/TABLE/WOOD013.JPG=GFX/TextureS/Table/wood013.jpg
GFX/TEXTURES/TRANSPORTER/BLUE BACKWALL.PNG=GFX/TEXTURES/TRANSPORTER/BLUE BACKWALL.PNG
GFX/TEXTURES/TRANSPORTER/BLUE BACKWALL_LV.PNG=GFX/TEXTURES/TRANSPORTER/BLUE BACKWALL_LV.PNG
GFX/TEXTURES/TRANSPORTER/BLUE BACKWALL_RV.PNG=GFX/TEXTURES/TRANSPORTER/BLUE BACKWALL_RV.PNG
GFX/TEXTURES/TRANSPORTER/SS_PAD.PNG=GFX/Textures/Transporter/SS_Pad.png
GFX/TEXTURES/WATER/WATER.PNG=GFX/TextureS/Water/water.png
GFX/TEXTURES/WHOLE/KITCHEN.PNG=GFX/Textures/Whole/Kitchen.png
GFX/TRANS/GENERAL.PNG=GFX/Trans/General.png
GFX/TRANS/RECOVER.PNG=GFX/Trans/Recover.png
GFX/TRANS/RETURNONLY.PNG=GFX/Trans/ReturnOnly.png
GFX/TREASURE/ARMS_CHEST.PNG=GFX/Treasure/ARMS_Chest.png
GFX/TREASURE/BAG.PNG=GFX/Treasure/Bag.png
GFX/TREASURE/TREASURECHEST.PNG=GFX/Treasure/TreasureChest.png
[TRANSFER]
UNKNOWN_ALLOWED=Y
