# Star Story - Episode 2 - The Virus Strikes Back
# Jeroen P. Broks
# 
# (c) Jeroen P. Broks, 2026

[AA_META]
01_TITLE=Star Story - Episode 2 - The Virus Strikes Back
02_CREATEDBY=Jeroen P. Broks
03_COPYRIGHT=(c) Jeroen P. Broks, 2026
04_LICENSE=Story Based Scripts are close license only publishe for evaluation purposes, others zlib
[DIRECTORY]
SCI_ASSETS_MULTIDIR=Y
[DIRECTORY::LINUX]
SCI_ASSETS_SOURCE=src/Assets
*list:LIBRARIES
	../Libs/SCI
	../Libs/General
	/media/tricky/Scyndi/Projects/Applications/Slyvina/Apps/SCI/SCI_Exe/IntLibs
*end
*list:SOURCEFILES
	src/Code
*end
[PROJECT]
AUTHOR=Jeroen P. Broks
COPYRIGHT=(c) Jeroen P. Broks, 2026
CREATED=16 Mar 2026; 22:10:16
DEBUGJQLDIR=Debug
LICENSE=Story Based Scripts are close license only publishe for evaluation purposes, others zlib
OUTPUTNAME=Star Story - Episode 2 - The Virus Strikes Back
TITLE=Star Story - Episode 2 - The Virus Strikes Back
[SCI::MOUSE]
HIDE=Y
[SCI::SAVE]
DIR=Star Story 2
ID=c735252e2d70616455b4735497586256-62177ad7b783fc734476d04618846302
[SCI::WINDOW]
ALTHEIGHT=95%
ALTWIDTH=99%
CAPTION=Star Story - Episode 2 - The Virus Strikes Back
FULL SCREEN=N
USEALT=Y
WINADEPTALT=Y
WINHEIGHT=1000
WINWIDTH=1200
[SCRIPT]
BYTECODE=Y
PACKAGE=*MAIN
[MERGE]
*list:MERGE
*end
