# Star Story - Episode 2 - The Virus Strikes Back
# Jeroen P. Broks
# 
# (c) Jeroen P. Broks, 2026

[AA_META]
01_TITLE=Star Story - Episode 2 - The Virus Strikes Back
02_CREATEDBY=Jeroen P. Broks
03_COPYRIGHT=(c) Jeroen P. Broks, 2026
04_LICENSE=Story Based Scripts are close license only publishe for evaluation purposes, others zlib
[DIRECTORY]
SCI_ASSETS_MULTIDIR=Y
[DIRECTORY::LINUX]
SCI_ASSETS_SOURCE=src/Assets
*list:LIBRARIES
	../Libs/SCI
	../Libs/General
	/media/tricky/Scyndi/Projects/Applications/Slyvina/Apps/SCI/SCI_Exe/IntLibs
*end
*list:SOURCEFILES
	src/Code
*end
[PROJECT]
AUTHOR=Jeroen P. Broks
COPYRIGHT=(c) Jeroen P. Broks, 2026
CREATED=16 Mar 2026; 22:10:16
DEBUGJQLDIR=Debug
LICENSE=Story Based Scripts are close license only publishe for evaluation purposes, others zlib
OUTPUTNAME=Star Story - Episode 2 - The Virus Strikes Back
TITLE=Star Story - Episode 2 - The Virus Strikes Back
[SCI::MOUSE]
HIDE=Y
[SCI::SAVE]
DIR=Star Story 2
ID=c735252e2d70616455b4735497586256-62177ad7b783fc734476d04618846302
[SCI::WINDOW]
ALTHEIGHT=95%
ALTWIDTH=99%
CAPTION=Star Story - Episode 2 - The Virus Strikes Back
FULL SCREEN=N
USEALT=Y
WINADEPTALT=Y
WINHEIGHT=1000
WINWIDTH=1200
[SCRIPT]
BYTECODE=Y
PACKAGE=*MAIN
[MERGE]
*list:MERGE
*end

[ASSETS_MULTIDIR::ANARRES]
ALLOWED=YES
AUTHOR=anarres
NOTES=Public Domain (Some of the graphics acredited to anarres may have been ripped from glitchthegame.com. Not really a problem since the assets have neen CC0 (public domain) licensed anyway)
PACKAGE=ASSETS
[ASSETS_MULTIDIR::BARNHEARTOWL]
ALLOWED=YES
AUTHOR=barnheartowl
NOTES=Public Domain
PACKAGE=Assets
[ASSETS_MULTIDIR::BENBONCAN]
ALLOWED=YES
AUTHOR=Benboncan
NOTES=Creative Commons - By Attribution
PACKAGE=ASSETS
[ASSETS_MULTIDIR::BRIAN KENT]
ALLOWED=YES
AUTHOR=Brian Kent
NOTES=Freeware
PACKAGE=ASSETS
[ASSETS_MULTIDIR::CAMELTECH]
ALLOWED=YES
AUTHOR=cameltech
NOTES=Public Domain
PACKAGE=assets
[ASSETS_MULTIDIR::DEAR_THEOPHILUS]
ALLOWED=YES
AUTHOR=dear_theophilus
NOTES=Public Domain
PACKAGE=Assets
[ASSETS_MULTIDIR::DEDICATED TEACHER]
ALLOWED=YES
AUTHOR=Public Domain
NOTES=Public Domain
PACKAGE=ASSETS
[ASSETS_MULTIDIR::DELUGE]
ALLOWED=YES
AUTHOR=Deluge
NOTES=Public Domain
PACKAGE=Assets
[ASSETS_MULTIDIR::DIVERSE BRONNEN]
ALLOWED=YES
AUTHOR=Diverse Bronnen
NOTES=If you are the photographer and want this picture removed, just let me know and I will make it happen A.S.A.P. -- I am NOT interested in the privacy of these 'cops'. Only in the copyrights of the photographers!
PACKAGE=ASSETS
[ASSETS_MULTIDIR::EADY]
ALLOWED=YES
AUTHOR=eady
NOTES=Public Domain
PACKAGE=Assets
[ASSETS_MULTIDIR::EVENT HORIZON TELESCOPE]
ALLOWED=YES
AUTHOR=Event Horizon Telescope
NOTES=Creative commons: By attribute
PACKAGE=ASSETS
[ASSETS_MULTIDIR::FABUIO]
ALLOWED=YES
AUTHOR=Fabuio
NOTES=Public Domain
PACKAGE=Assets
[ASSETS_MULTIDIR::FESLIYAN STUDIOS]
ALLOWED=YES
AUTHOR=Fesliyan Studios
NOTES=For license, please check their own website: https://www.fesliyanstudios.com/sound-effects-policy
PACKAGE=ASSETS
[ASSETS_MULTIDIR::FIFTYSOUNDS.COM]
ALLOWED=YES
AUTHOR=fiftysounds.com
NOTES=Free for commercial and non-commercial use. -- Unlimited projects, worldwide, forever. -- Attribution is not required. Giving credit to FiftySounds is not necessary but is always appreciated.
PACKAGE=Assets
[ASSETS_MULTIDIR::FINAO123]
ALLOWED=YES
AUTHOR=finao123
NOTES=Public Domain
PACKAGE=Assets
[ASSETS_MULTIDIR::FIRKIN & JEROEN P. BROKS]
ALLOWED=YES
AUTHOR=Firkin & Jeroen P. Broks
NOTES=Line drawing by Firkin, colored by Jeroen P. Broks - Public Domain
PACKAGE=ASSETS
[ASSETS_MULTIDIR::FLYING DUTCHMAN]
ALLOWED=YES
AUTHOR=Flying Dutchman
NOTES=Public Domain
PACKAGE=ASSETS
[ASSETS_MULTIDIR::FRANKES]
ALLOWED=YES
AUTHOR=frankes
NOTES=Public Domain
PACKAGE=ASSETS
[ASSETS_MULTIDIR::FREESFX.CO.UK]
ALLOWED=YES
AUTHOR=freesfx.co.uk
NOTES=https://www.freesfx.co.uk/Page/4/End-User-License-Agreement
PACKAGE=ASSETS
[ASSETS_MULTIDIR::GDJ]
ALLOWED=YES
AUTHOR=GDJ
NOTES=Public Domain
PACKAGE=ASSETS
[ASSETS_MULTIDIR::GLITCH]
ALLOWED=YES
AUTHOR=glitch
NOTES=Public Domain
PACKAGE=ASSETS
[ASSETS_MULTIDIR::GRAMZON]
ALLOWED=YES
AUTHOR=gramzon
NOTES=Public Domain
PACKAGE=Assets
[ASSETS_MULTIDIR::GR-SITES]
ALLOWED=YES
AUTHOR=GR-Sites
NOTES=Free stuff from unknown authors.
PACKAGE=Assets
[ASSETS_MULTIDIR::GSAGRI04]
ALLOWED=YES
AUTHOR=gsagri04
NOTES=Public Domain
PACKAGE=Assets
[ASSETS_MULTIDIR::HATALAR]
ALLOWED=YES
AUTHOR=hatalar
NOTES=Public Domain
PACKAGE=Assets
[ASSETS_MULTIDIR::HOTTA]
ALLOWED=YES
AUTHOR=hotta
NOTES=Public Domain
PACKAGE=Assets
[ASSETS_MULTIDIR::HYPOCORE]
ALLOWED=YES
AUTHOR=hypocore
NOTES=Public Domain
PACKAGE=ASSETS
[ASSETS_MULTIDIR::INKY2010]
ALLOWED=YES
AUTHOR=Inky2010
NOTES=Public Domain
PACKAGE=Assets
[ASSETS_MULTIDIR::J_ALVES]
ALLOWED=YES
AUTHOR=J_Alves
NOTES=Public Domain
PACKAGE=ASSETS
[ASSETS_MULTIDIR::J4P4N]
ALLOWED=YES
AUTHOR=J4p4n
NOTES=Public Domain
PACKAGE=Assets
[ASSETS_MULTIDIR::JONATA]
ALLOWED=YES
AUTHOR=Jonata
NOTES=Public Domain
PACKAGE=ASSETS
[ASSETS_MULTIDIR::JPD2010]
ALLOWED=YES
AUTHOR=jpd2010
NOTES=Public Domain
PACKAGE=Assets
[ASSETS_MULTIDIR::JQL]
ALLOWED=YES
AUTHOR=When you see this, you are dealing with a JQL imported file of which the data was not properly transferred into this project. Please notify Jeroen P. Broks about that.
NOTES=When you see this, you are dealing with a JQL imported file of which the data was not properly transferred into this project. Please notify Jeroen P. Broks about that.
PACKAGE=JQL
[ASSETS_MULTIDIR::JQL_MUSIC]
ALLOWED=YES
AUTHOR=This message should NEVER appear! If it still does, we got a problem
NOTES=This message should NEVER appear! If it still does, we got a problem
PACKAGE=MUSIC
[ASSETS_MULTIDIR::JUHELLE]
ALLOWED=YES
AUTHOR=Juhelle
NOTES=Public Domain
PACKAGE=ASSETS
[ASSETS_MULTIDIR::KELLY]
ALLOWED=YES
AUTHOR=Kelly
NOTES=Public Domain
PACKAGE=ASSETS
[ASSETS_MULTIDIR::KERNSCHALL]
ALLOWED=YES
AUTHOR=kernschall
NOTES=This work is licensed under the Creative Commons Attribution License.
PACKAGE=Assets
[ASSETS_MULTIDIR::LIFTARN & JEROEN P. BROKS]
ALLOWED=YES
AUTHOR=liftarn & Jeroen P. Broks
NOTES=Line Drawing by liftarn, coloring by Jeroen P. Broks. Public Domain
PACKAGE=ASSETS
[ASSETS_MULTIDIR::LINVALA]
ALLOWED=YES
AUTHOR=Linvala
NOTES=This art was created specifically as part of the Phantasar Chronicles and may therefore not be extracted from the game without prior written permission from Jeroen P. Broks
PACKAGE=Assets
[ASSETS_MULTIDIR::MAN OF STEEL]
ALLOWED=YES
AUTHOR=Man Of Steel
NOTES=Due to these files being transferred from another project some unclarity can exist about the exact license.
PACKAGE=Assets
[ASSETS_MULTIDIR::MAN OF STEEL CC]
ALLOWED=YES
AUTHOR=Man of Steel
NOTES=Creative Commons - By Attribute - Non-Commercial - Share-Alike
PACKAGE=Assets
[ASSETS_MULTIDIR::MAP BANNERS]
ALLOWED=YES
AUTHOR=Jeroen P. Broks
NOTES=Names of maps are specific to this game. Not to be extracted from this game without prior written permission from Jeroen P. Broks
PACKAGE=Assets
[ASSETS_MULTIDIR::MERLIN2525]
ALLOWED=YES
AUTHOR=Merlin2525
NOTES=Public Domain
PACKAGE=Assets
[ASSETS_MULTIDIR::MICHAEL FRANK]
ALLOWED=YES
AUTHOR=Michael Frank
NOTES=Public Domain
PACKAGE=ASSETS
[ASSETS_MULTIDIR::MIONI]
ALLOWED=YES
AUTHOR=Mioni
NOTES=PUBLIC DOMAIN
PACKAGE=ASSETS
[ASSETS_MULTIDIR::MOHAMMED IBRAHIM]
ALLOWED=YES
AUTHOR=Mohammed Ibrahim
NOTES=Public Domain
PACKAGE=ASSETS
[ASSETS_MULTIDIR::MUSIC]
ALLOWED=YES
AUTHOR=Jeroen P. Broks
NOTES=Don't bother! All this file had to do was to exist!
PACKAGE=MUSIC
[ASSETS_MULTIDIR::MUSIC_ERIC_MATYAS]
ALLOWED=YES
AUTHOR=Eric Matyas
NOTES=Please check the website www.soundimage.org for the exact terms. Don't extract this file prior to checking those terms!
PACKAGE=MUSIC
[ASSETS_MULTIDIR::NASA]
ALLOWED=YES
AUTHOR=NASA
NOTES=Public Domain
PACKAGE=ASSETS
[ASSETS_MULTIDIR::OCAL]
ALLOWED=YES
AUTHOR=Random Artists from the Open Clip Art Library
NOTES=Public Domain
PACKAGE=ASSETS
[ASSETS_MULTIDIR::PABLO  IMPALLARI]
ALLOWED=YES
AUTHOR=Pablo  Impallari
NOTES=SIL Open fonts license
PACKAGE=assets
[ASSETS_MULTIDIR::PACDV]
ALLOWED=YES
AUTHOR=PacDV
NOTES=This file was downloaded from PacDV.com and I was allowed to use it for free. This file may NOT be extracted from the Resource.JCR file, it must be obtained from its original source http://www.pacdv.com -- Thank you!
PACKAGE=ASSETS
[ASSETS_MULTIDIR::RAY LARABIE]
ALLOWED=YES
AUTHOR=Ray Larabie
NOTES=Font lic
PACKAGE=ASSETS
[ASSETS_MULTIDIR::RFC1394]
ALLOWED=YES
AUTHOR=rfc1394
NOTES=Public Domain
PACKAGE=Assets
[ASSETS_MULTIDIR::S]
ALLOWED=YES
AUTHOR=?
NOTES=?
PACKAGE=Assets
[ASSETS_MULTIDIR::SEV]
ALLOWED=YES
AUTHOR=Sev
NOTES=Public Domain
PACKAGE=ASSETS
[ASSETS_MULTIDIR::SKURIAN25]
ALLOWED=YES
AUTHOR=Skurian25
NOTES=Public Domain
PACKAGE=ASSETS
[ASSETS_MULTIDIR::SOUNDSCRATE]
ALLOWED=YES
AUTHOR=SoundsCrate
NOTES=CC-BY 2.0
PACKAGE=Assets
[ASSETS_MULTIDIR::THEGRAPHICGIRL]
ALLOWED=YES
AUTHOR=TheGraphicGirl
NOTES=Public Domain
PACKAGE=Assets
[ASSETS_MULTIDIR::TRICKY & MANOFSTEEL]
ALLOWED=YES
AUTHOR=Jeroen P. Broks & Man Of Steel
NOTES=Don't extract any of these files unless you have written permission by Jeroen P. Broks
PACKAGE=Assets
[ASSETS_MULTIDIR::TRICKY CC]
ALLOWED=YES
AUTHOR=Jeroen P. Broks
NOTES=Creative Commons - By Attribute - Non-Commercial - Share-Alike
PACKAGE=ASSETS
[ASSETS_MULTIDIR::TRICKY PRIVATE]
ALLOWED=YES
AUTHOR=Jeroen P. Broks
NOTES=This file may NOT be extracted from this package without prior written permission by Jeroen P. Broks
PACKAGE=ASSETS
[ASSETS_MULTIDIR::TRICKY SCRIPT]
ALLOWED=YES
AUTHOR=Jeroen P. Broks
NOTES=Scripts dedicated to the story line may NOT be extracted and may only be viewed for evaluation purposes. Scripts non dedicated to the story line can still contain story references which must be stripped, once stripped of all that you may use these under the terms of the zlib license. Please check the copyright notice at the top of each script file
PACKAGE=Script
[ASSETS_MULTIDIR::TRICKY STORY]
ALLOWED=YES
AUTHOR=Jeroen P. Broks
NOTES=This file may NOT be extracted from this package without prior written permission by Jeroen P. Broks
PACKAGE=STORY
[ASSETS_MULTIDIR::TRICKY TRANSFER]
ALLOWED=YES
AUTHOR=Jeroen P. Broks
NOTES=These are files that came in due to a Kthura Map transfer, and the license could therefore be unclear and in need to be sorted out.
PACKAGE=ASSETS
[ASSETS_MULTIDIR::UNKNOWN]
ALLOWED=YES
AUTHOR=Unknown Person
NOTES=The artist and full license are unknown, yet this was offered through sites offering free assets. Should you be the copyright holder, please contact me and show me proof you are the copyright holder, if you want this stuff removed.
PACKAGE=Assets
[ASSETS_MULTIDIR::VARAZUVI(TM)]
ALLOWED=YES
AUTHOR=Varazuvi(TM)
NOTES=Copyright (c) Varazuvi(tm) www.varazuvi.com - Licensed under a creative commons attribution license.
PACKAGE=Assets
[ASSETS_MULTIDIR::VICIOUS SPEED]
ALLOWED=YES
AUTHOR=Vicious Speed
NOTES=Public Domain
PACKAGE=Assets
[ASSETS_MULTIDIR::WARSZAWIANKA]
ALLOWED=YES
AUTHOR=warszawianka
NOTES=Public Domain
PACKAGE=ASSETS
[ASSETS_MULTIDIR::WESD444 & JEROEN P. BROKS]
ALLOWED=YES
AUTHOR=wesd444 & Jeroen P. Broks
NOTES=Sketch (line drawing) provided by wesd444 as public domain. Colored by Jeroen P. Broks. Result picture is CC-BY
PACKAGE=ASSETS
[ASSETS_MULTIDIR::WIDZY]
ALLOWED=YES
AUTHOR=Widzy
NOTES=File may only be used with permission from Widzy
PACKAGE=ASSETS

